export enum EActividades {
  NUEVO_FOLIO = 1,
  SOLICITUD = 2,
  CARGA_DOCUMENTAL = 3,
  VALIDACION_DIGITAL = 4,
  FIRMA_CLIENTE = 5,
  FIRMA_EJECUTIVO = 6,
  VALIDACION_DE_FIRMAS = 7,
  CONFIRMACION_DE_ENTREGA = 8,
  CONTACTO_TELEFONICO = 9,
  CONTACTO_ASEGURADORA = 10,
  DICTAMEN_MEDICO = 11,
  CONSULTA = 12,
  CONSULTA_EXCEPCION = 13,
  GENERACION_DE_PAGO = 14,
  LIBERA_PAGO = 15,
  GENERACION_FINIQUITO = 16,
  FIRMA_FINIQUITO = 17,
  RECOLECCION_DE_FISICOS = 18,
  VALIDACION_DE_ORIGINALES = 19,
  RECEPCION_DE_ORIGINALES = 20,
  NUEVA_COTIZACION = 21,
  ANALISIS_DE_COTIZACION = 22,
  ELABORACION_DE_COTIZACION = 23,
  REVISION_COTIZACION = 24,
  ENVIO_COTIZACION = 25,
  COTIZACION_FINAL = 26,
  CUADRE_COTIZACION = 27,
  GENERACION_DE_FORMATOS = 28,
  VALIDACION_AFIANZADORA = 29,
  INFORMACION_ACLARATORIA = 30,
  FINALIZADO = 0,
}


export const FlujoActividades: Record<number, {
  iconCompleted: string,
  iconInProgress: string,
  iconNotStarted: string,
  name: string,
  actividad: number,
  url: string,
  type: number,
}> =  {
  1: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/nuevo_folio.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/nuevo_folio.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/nuevo_folio.notstarted.svg',
    name: 'Nuevo folio',
    actividad: 1,
    url: `PROYECTO_URL/nuevo-folio`,
    type: 1,
  },
  2: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/solicitud.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/solicitud.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/solicitud.notstarted.svg',
    name: 'Solicitud',
    actividad: 2,
    url: `PROYECTO_URL/solicitud`,
    type: 1,
  },
  3: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/carga_documental.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/carga_documental.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/carga_documental.notstarted.svg',
    name: 'Carga documental',
    actividad: 3,
    url: `PROYECTO_URL/carga-documental/FOLIO_ID`,
    type: 2,
  },
  4: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/validacion_documental.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/validacion_documental.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/validacion_documental.notstarted.svg',
    name: 'Validación documental',
    actividad: 4,
    url: `PROYECTO_URL/validacion-documental/FOLIO_ID`,
    type: 2,
  },
  5: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/firma_cliente.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/firma_cliente.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/firma_cliente.notstarted.svg',
    name: 'Firma documental',
    actividad: 5,
    url: `PROYECTO_URL/firma-cliente/FOLIO_ID`,
    type: 2,
  },
  6: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/firma_ejecutivo.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/firma_ejecutivo.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/firma_ejecutivo.notstarted.svg',
    name: 'Firma rjecutivo',
    actividad: 6,
    url: `PROYECTO_URL/firma-ejecutivo/FOLIO_ID`,
    type: 2,
  },
  7: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/validacion_firma.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/validacion_firma.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/validacion_firma.notstarted.svg',
    name: 'Validación de firmas',
    actividad: 7,
    url: `PROYECTO_URL/validacion-firmas/FOLIO_ID`,
    type: 2,
  },
  8: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/confirmacion_entrega.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/confirmacion_entrega.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/confirmacion_entrega.notstarted.svg',
    name: 'Confirmación de entrega',
    actividad: 8,
    url: `PROYECTO_URL/confirmacion-entrega/FOLIO_ID`,
    type: 2,
  },
  9: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/contacto_telefonico.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/contacto_telefonico.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/contacto_telefonico.notstarted.svg',
    name: 'Contacto telefonico',
    actividad: 9,
    url: `PROYECTO_URL/contacto-telefonico/FOLIO_ID`,
    type: 2,
  },
  10: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/contacto_aseguradora.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/contacto_aseguradora.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/contacto_aseguradora.notstarted.svg',
    name: 'Contacto aseguradora',
    actividad: 10,
    url: `PROYECTO_URL/contacto-aseguradora/FOLIO_ID`,
    type: 2,
  },
  11: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/dictamen_medico.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/dictamen_medico.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/dictamen_medico.notstarted.svg',
    name: 'Dictamen medico',
    actividad: 11,
    url: `PROYECTO_URL/dictamen-medico/FOLIO_ID`,
    type: 3,
  },
  12: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/consulta.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/consulta.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/consulta.notstarted.svg',
    name: 'Consulta',
    actividad: 12,
    url: `PROYECTO_URL/consulta/FOLIO_ID`,
    type: 3,
  },
  13: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/consulta_excepcion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/consulta_excepcion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/consulta_excepcion.notstarted.svg',
    name: 'Consulta excepcion',
    actividad: 13,
    url: `PROYECTO_URL/consulta-excepcion/FOLIO_ID`,
    type: 3,
  },
  14: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/generacion_pago.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/generacion_pago.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/generacion_pago.notstarted.svg',
    name: 'Generación de pago',
    actividad: 14,
    url: `PROYECTO_URL/generacion-pago/FOLIO_ID`,
    type: 2,
  },
  15: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/libera_pago.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/libera_pago.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/libera_pago.notstarted.svg',
    name: 'Libera pago',
    actividad: 15,
    url: `PROYECTO_URL/libera-pago/FOLIO_ID`,
    type: 2,
  },
  16: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/generacion_finiquito.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/generacion_finiquito.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/generacion_finiquito.notstarted.svg',
    name: 'Generación finiquito',
    actividad: 16,
    url: `PROYECTO_URL/generacion-finiquito/FOLIO_ID`,
    type: 2,
  },
  17: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/firma_finiquito.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/firma_finiquito.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/firma_finiquito.notstarted.svg',
    name: 'Firma finiquito',
    actividad: 17,
    url: `PROYECTO_URL/firma-finiquito/FOLIO_ID`,
    type: 2,
  },
  18: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/recoleccion_fisicos.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/recoleccion_fisicos.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/recoleccion_fisicos.notstarted.svg',
    name: 'Recolección de fisicos',
    actividad: 18,
    url: `PROYECTO_URL/recoleccion-fisicos/FOLIO_ID`,
    type: 3,
  },
  19: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/validacion_originales.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/validacion_originales.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/validacion_originales.notstarted.svg',
    name: 'Validación de originales',
    actividad: 19,
    url: `PROYECTO_URL/validacion-originales/FOLIO_ID`,
    type: 3,
  },
  20: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/recepcion_originales.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/recepcion_originales.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/recepcion_originales.notstarted.svg',
    name: 'Recepción de originales',
    actividad: 20,
    url: `PROYECTO_URL/recepcion-originales/FOLIO_ID`,
    type: 3,
  },
  21: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/nueva_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/nueva_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/nueva_cotizacion.notstarted.svg',
    name: 'Nueva cotización',
    actividad: 21,
    url: `PROYECTO_URL/nueva-cotizacion/FOLIO_ID`,
    type: 3,
  },
  22: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/analisis_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/analisis_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/analisis_cotizacion.notstarted.svg',
    name: 'Analisis cotización',
    actividad: 22,
    url: `PROYECTO_URL/analisis-cotizacion/FOLIO_ID`,
    type: 3,
  },
  23: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/elaboracion_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/elaboracion_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/elaboracion_cotizacion.notstarted.svg',
    name: 'Elaboración de cotización',
    actividad: 23,
    url: `PROYECTO_URL/elaboracion-cotizacion/FOLIO_ID`,
    type: 3,
  },
  24: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/revision_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/revision_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/revision_cotizacion.notstarted.svg',
    name: 'Revisión cotización',
    actividad: 24,
    url: `PROYECTO_URL/revision-cotizacion/FOLIO_ID`,
    type: 3,
  },
  25: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/envio_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/envio_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/envio_cotizacion.notstarted.svg',
    name: 'Envió cotización',
    actividad: 25,
    url: `PROYECTO_URL/envio-cotizacion/FOLIO_ID`,
    type: 3,
  },
  26: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/cotizacion_final.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/cotizacion_final.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/cotizacion_final.notstarted.svg',
    name: 'Cotización final',
    actividad: 26,
    url: `PROYECTO_URL/cotizacion-final/FOLIO_ID`,
    type: 3,
  },
  27: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/cuadre_cotizacion.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/cuadre_cotizacion.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/cuadre_cotizacion.notstarted.svg',
    name: 'Cuadre cotización',
    actividad: 27,
    url: `PROYECTO_URL/cuadre-cotizacion/FOLIO_ID`,
    type: 3,
  },
  28: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/generacion_formatos.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/generacion_formatos.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/generacion_formatos.notstarted.svg',
    name: 'Generación de formatos',
    actividad: 28,
    url: `PROYECTO_URL/generacion-formatos/FOLIO_ID`,
    type: 3,
  },
  29: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.notstarted.svg',
    name: 'Validación afianzadora',
    actividad: 29,
    url: `PROYECTO_URL/validacion-afianzadora/FOLIO_ID`,
    type: 3,
  },
  30: {
    iconCompleted: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.completed.svg',
    iconInProgress: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.inprogress.svg',
    iconNotStarted: 'assets/images/flujo-consulta/flujo/validacion_afianzadora.notstarted.svg',
    name: 'Información aclaratoria',
    actividad: 30,
    url: `PROYECTO_URL/informacion-aclaratoria/FOLIO_ID`,
    type: 3,
  }
};


export const BitacoraActividades: Record<number, string> =  {
  0: 'COMPLETADO',
  1: ' ',
  2: 'EN SOLICITUD',
  3: 'PENDIENTE DE DOCUMENTACIÓN',
  4: 'EN PROCESO DE GESTIÓN',
  5: '',
  6: '',
  7: '',
  8: '',
  9: '',
  10: '',
  11: 'EN DICTAMEN MÉDICO',
  12: 'EN CONSULTA',
  13: '',
  14: 'EN PROCESO DE PAGO',
  15: 'EN LIBERACIÓN DE PAGO',
  16: '',
  17: '',
  18: '',
  19: '',
  20: '',
  21: '',
  22: '',
  23: '',
  24: '',
  25: '',
  26: '',
  27: '',
  28: '',
  29: '',
  30: ''
};
