export const FnzConsts = {
  PERMISSIONS: {
    dashboard: 'dashboard',
    bandeja_entradas: 'bandeja-entrada',
    bandeja_reprocesos: 'bandeja-reproceso',
    bandeja_suspendidas: 'bandeja-suspendida',
    bandeja_programadas: 'bandeja-programada',
    busquedas: 'busquedas',
    nuevo_folio: 'nuevo-folio',
    solicitud: 'solicitud',
    carga_documental: 'carga-documental',
    validacion_digital: 'validacion-digital',
    generacion_formatos: 'generacion-formatos',
    firma_documental: 'firma-documental',
    validacion_firma: 'validacion-firma',
    validacion_afianzadora: 'validacion-afianzadora',
    recoleccion_fisicos: 'recoleccion-fisicos',
    validacion_originales: 'validacion-originales',
    confirmacion_entrega: 'confirmacion-entrega',
    contacto_telefonico: 'contacto-telefonico',
    contacto_aseguradora: 'contacto-aseguradora',
    carga_documental_masiva: 'carga-documental-masiva',
  },
};
